name: portfolio
description: "My Portfolio Web App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.6
  url_launcher_platform_interface: ^2.3.2
  flutter_animated_button: ^2.0.3
  intl: ^0.19.0
  http: ^1.2.1
  animate_do: ^3.3.4
  transparent_image: ^2.0.1
  flutter_svg: ^2.0.10+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/repo_images/
    - assets/images/repo_images/pomodoro/
    - assets/images/repo_images/movie/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Scada
      fonts:
        - asset: assets/fonts/Scada-Regular.ttf
        - asset: assets/fonts/Scada-Italic.ttf
          style: italic
        - asset: assets/fonts/Scada-Bold.ttf
          weight: 700
        - asset: assets/fonts/Scada-BoldItalic.ttf
          style: italic
          weight: 700