name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      
      - name: Getting on Github Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /portfolio/
          webRenderer: canvaskit
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email brunoca2000@hotmail.com
          git config --global user.name Bruno Coelho
          git status
          git remote add origin https://${{secrets.PORTFOLIO_TOKEN}}@github.com/BrunoRabbit/BrunoRabbit.github.io.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
