name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      
      - name: Getting on Github Pages
        uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /portfolio/
          webRenderer: canvaskit
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      
